<?php


namespace App\Service;

use Twig\Extension\AbstractExtension;
use Twig\TwigFilter;

class TwigExtension extends AbstractExtension
{
    public function getFilters()
    {
        return [
            new TwigFilter('price', [$this, 'priceFilter'])
        ];
    }

    public function getFunctions()
    {
        return parent::getFunctions(); // TODO: Change the autogenerated stub
    }

    public function priceFilter(float $price): string {
        return round($price, 2) . '€';
    }

}